### ISSUE TITLE
Can't disable jit and still run diffeqsolve on GPU

### ISSUE THREAD

**Issue by cgiovanetti** [patrick-kidger/diffrax#293]
I'm doing some debugging and wanted to disable jit, rather than commenting out each decorator manually, so I added 

```
from jax.config import config
config.update('jax_disable_jit', True)
```

to the top of my script.  When I ran on GPU, my code broke, with the error

`jax._src.traceback_util.UnfilteredStackTrace: ValueError: Closure-converted function called with different dynamic arguments to the example arguments provided.`

I'll include the full error message I got at the bottom of this message.  Here's a minimal script that reproduces the issue:

```
import jax
import jax.numpy as jnp 

from diffrax import diffeqsolve, ODETerm, Dopri5, PIDController, SaveAt

from jax.config import config
config.update('jax_disable_jit', True)

def get_t():

    rho_tot_vec = jnp.logspace(-3, 3,num=1000)

    def dt_prime(rho_tot, t, args): 
        return 1. / (-3.  *(rho_tot))

    rho_tot_init = rho_tot_vec[0]
    rho_tot_fin  = rho_tot_vec[-1]

    sol_t = diffeqsolve(
        ODETerm(dt_prime), Dopri5(), 
        t0=rho_tot_init, t1=rho_tot_fin, 
        y0=1. / (2 ), dt0=None, max_steps=4096,
        saveat=SaveAt(ts=rho_tot_vec), stepsize_controller=PIDController(rtol=1e-4, atol=1e-4)
    )

    return sol_t.ys

def runCode():
    return get_t()/2

runCode()
```

I don't get any such error running on CPU.  The GPU I was running on was a Quadro RTX 8000, though I've tried on some other GPUs on my university's cluster and got the same result.  My version of diffrax is 0.4.0.

Here's the full error message:
```
Traceback (most recent call last):
  File "<filepath>/diffrax_jit_test.py", line 32, in <module>
    runCode()
  File "<filepath>/diffrax_jit_test.py", line 30, in runCode
    return get_t()/2
  File "<filepath>/diffrax_jit_test.py", line 20, in get_t
    sol_t = diffeqsolve(
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_jit.py", line 102, in __call__
    return self._call(False, args, kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_jit.py", line 98, in _call
    out = self._cached(dynamic, static)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_jit.py", line 36, in fun_wrapped
    out = fun(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/diffrax/integrate.py", line 794, in diffeqsolve
    final_state, aux_stats = adjoint.loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/diffrax/adjoint.py", line 286, in loop
    final_state = self._loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/diffrax/integrate.py", line 401, in loop
    final_state = outer_while_loop(
  File "/ext3/miniconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/internal/_loop/loop.py", line 107, in while_loop
    return checkpointed_while_loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/internal/_loop/checkpointed.py", line 249, in checkpointed_while_loop
    _, _, _, final_val = _checkpointed_while_loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_ad.py", line 869, in __call__
    out = self.fn_wrapped(
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/custom_derivatives.py", line 617, in __call__
    out_flat = custom_vjp_call_p.bind(flat_fun, flat_fwd, flat_bwd,
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/custom_derivatives.py", line 766, in bind
    outs = top_trace.process_custom_vjp_call(self, fun, fwd, bwd_, tracers,
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/core.py", line 834, in process_custom_vjp_call
    return fun.call_wrapped(*tracers)
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_ad.py", line 778, in fn_wrapped
    out = self.fn(vjp_arg, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/internal/_loop/checkpointed.py", line 269, in _checkpointed_while_loop
    return while_loop(cond_fun, _body_fun, init_val)
  File "/ext3/miniconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1120, in while_loop
    while cond_fun(val):
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_ad.py", line 423, in __call__
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Closure-converted function called with different dynamic arguments to the example arguments provided.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<filepath>/diffrax_jit_test.py", line 32, in <module>
    runCode()
  File "<filepath>/diffrax_jit_test.py", line 30, in runCode
    return get_t()/2
  File "<filepath>/diffrax_jit_test.py", line 20, in get_t
    sol_t = diffeqsolve(
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_jit.py", line 102, in __call__
    return self._call(False, args, kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_jit.py", line 98, in _call
    out = self._cached(dynamic, static)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_jit.py", line 36, in fun_wrapped
    out = fun(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/diffrax/integrate.py", line 794, in diffeqsolve
    final_state, aux_stats = adjoint.loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/diffrax/adjoint.py", line 286, in loop
    final_state = self._loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/diffrax/integrate.py", line 401, in loop
    final_state = outer_while_loop(
  File "/ext3/miniconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/internal/_loop/loop.py", line 107, in while_loop
    return checkpointed_while_loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/internal/_loop/checkpointed.py", line 249, in checkpointed_while_loop
    _, _, _, final_val = _checkpointed_while_loop(
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_ad.py", line 869, in __call__
    out = self.fn_wrapped(
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_ad.py", line 778, in fn_wrapped
    out = self.fn(vjp_arg, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/internal/_loop/checkpointed.py", line 269, in _checkpointed_while_loop
    return while_loop(cond_fun, _body_fun, init_val)
  File "/ext3/miniconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/ext3/miniconda3/lib/python3.9/site-packages/equinox/_ad.py", line 423, in __call__
    raise ValueError(
ValueError: Closure-converted function called with different dynamic arguments to the example arguments provided.
```

**Comment by cgiovanetti** [comment]
The JAX folks got back to me (https://github.com/google/jax/issues/17156#issuecomment-1682516640), and suggested that this be resolved in user code, since there are situations where the current behavior might be desirable.

**Comment by joglekara** [comment]
So I am running into this same error on a Mac with and without `disable_jit` when I am only running a forward pass.

The code runs with `DirectAdjoint` but fails with `RecursiveCheckpointAdjoint`. 

Is this related to the upstream JAX discussion?

**Comment by patrick-kidger** [comment]
I believe this is an issue with specifically `disable_jit`. (And in the absence of an upstream fix in JAX, we should probably think about workiing around it here in Diffrax -- I think the fix will be to add a few `jnp.asarray`s in the right places.)

Do you have a MWE for the issue you're seeing?

**Comment by patrick-kidger** [comment]
For the original issue: in the absence of a fix in upstream JAX, this is now fixed in #322.

**Comment by puat133** [comment]
I found another related behavior. When the ODE function (`ODETerm`) passed to `diffeqsolve` is defined as a class inheriting from `eqx.Module`, disabling JIT (using `jax.config.update("jax_disable_jit", True)`) still results in traced arrays. 

Below is an example adapted from the stiff ODE example in the diffrax documentation. Even though JIT is disabled, the variable `y` inside the `__call__` method of the `Robertson` class shows up as `Traced<ShapedArray(float[3])>` during debugging. I expected it to be a normal `jax.numpy` array instead.

**Code Example:**

```python
import jax
jax.config.update("jax_enable_x64", True)
jax.config.update("jax_disable_jit", True)
import jax.numpy as jnp
import equinox as eqx
import diffrax as dfx

class Robertson(eqx.Module):
    k1: float
    k2: float
    k3: float

    def __call__(self, t, y, args):
        f0 = -self.k1 * y[0] + self.k3 * y[1] * y[2]
        f1 = self.k1 * y[0] - self.k2 * (y[1] ** 2) - self.k3 * y[1] * y[2]
        f2 = self.k2 * (y[1] ** 2)
        return jnp.stack([f0, f1, f2])

def run(k1=0.04, k2=3e7, k3=1e4):
    robertson = Robertson(k1, k2, k3)
    terms = dfx.ODETerm(robertson)
    t0, t1 = 0.0, 100.0
    y0 = jnp.array([1.0, 0.0, 0.0])
    dt0 = 0.0002
    solver = dfx.Kvaerno5()
    saveat = dfx.SaveAt(ts=jnp.array([0.0, 1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1, 1e2]))
    stepsize_controller = dfx.PIDController(rtol=1e-8, atol=1e-8)
    
    sol = dfx.diffeqsolve(
        terms,
        solver,
        t0,
        t1,
        dt0,
        y0,
        saveat=saveat,
        stepsize_controller=stepsize_controller,
    )
    return sol

if __name__ == '__main__':
    sol = run()
```

**Environment:**
- `diffrax 0.6.1`
- `equinox 0.11.10`
- `jax 0.4.37`
- `jaxlib 0.4.36`

**Question:**
Is this expected behavior when using `eqx.Module` with `diffrax` and `jax_disable_jit=True`? If not, what adjustments should be made to ensure `y` is a standard `jnp` array rather than a traced array?

**Comment by patrick-kidger** [comment]
I think that's expected, due to code like the following:
```python
import jax
jax.config.update("jax_disable_jit", True)

def f(x):
    print(x)

jax.eval_shape(f, 1)
```

**Comment by puat133** [comment]
I appreciate your explanation, but I'm still not entirely sure I understand. Are you suggesting that the state variables appear as traced arrays because the `__call__` method is only being invoked for shape evaluation (similar to what `jax.eval_shape ` does)? I was hoping that by disabling JIT, I'd be able to inspect the actual numerical values of the state variables directly.

**Comment by patrick-kidger** [comment]
Ah, I'm just noting that there are use-cases for which it's expected to see tracers even under disable-jit.

It's true that some point there will be runtime values. FWIW there are cases in which JAX will JIT even when disable-jit is enabled; the example I know about is batched while loops requiring JIT. I'd suggest throwing down a `breakpoint()` and inspecting the call stack to figure out why things don't appear to be disable-JIT'd.

(You can also use `jax.debug.print` to display values at runtime.)

**Comment by puat133** [comment]
Thanks for the suggestion!
